"""empty message

Revision ID: 21602cf41312
Revises: 50404cf21c0d
Create Date: 2024-06-26 07:48:46.358025

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21602cf41312'
down_revision = '50404cf21c0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorite')
    # ### end Alembic commands ###
